name: dochunt
channels:
  - defaults
  - conda-forge
dependencies:
  - nodejs>=15.0
  - python>=3.8,<3.9
  - numpy
  - scipy
  - conda-forge::jupyterlab
  - pip
  - pip:
    - flake8
    - gensim
    - fastapi
    - uvicorn[standard]
    - msal
    - PyJWT
