name: paper-scope
channels:
  - defaults
  - conda-forge
dependencies:
  - nodejs>=15.0
  - python>=3.8,<3.9
  - numpy
  - pandas
  - scipy
  - conda-forge::jupyterlab
  - pip
  - pip:
    - flake8
    - gensim
    - python-Levenshtein
    - fastapi
    - uvicorn[standard]
    - msal
    - python-jose[cryptography]
    - cryptography<3.4
    - httpx
    - pydantic
    - requests
    - sqlalchemy>=1.4
    - pyodbc
    - aiofiles
    - aiohttp
